### PR TITLE
Defaults and Collections are initialized using property initializers …

### PR DESCRIPTION
**Pull request by Drizin**
Defaults and Collections are initialized using property initializers (C# 6.0), so that Entity Constructors could be removed. This allows one to create their own constructors in partial classes, allowing mandatory arguments, private constructors, etc.

### CODE REVIEW

**Comment by ErikEJ** [comment]
I was under the impression that the generated code should be C# 5 compatible? But maybe it is time to make a breaking change?

**Comment by Drizin** [comment]
Erik, I was not aware of that restriction, but I think it makes sense. I can refactor that it into something configurable if you think it makes more sense.

**Comment by sjh37** [comment]
I've had previous requests to make it compilable with C# 5.
Accepting this pull request would work for you, but break other peoples build processes. See #196 for further details.
So would like to keep it working on C# 5 and above. For a little while at least...

**Comment by Drizin** [comment]
No problem, totally understand. Thank you for your attention to this matter.

In case someone else finds this PR useful, the reason is simple: I don't like empty constructors on my entities because I use mandatory parameters in constructors (or sometimes factories), and empty constructors allow API misuse.

**Pull request closed without merging**
