### PR TITLE
Hybrid annotations

### PR DESCRIPTION
**Pull request by daiplusplus**
See issue #434 

Adds `Settings.UseDataAnnotationsWithFluent` which causes a select subset of annotations to be applied to entity class properties which may be useful outside of Entity Framework.

### CODE REVIEW

**Comment by sjh37** [comment]
Dai, you are a true super star. I don't know what to say. Thank you.

**Comment by daiplusplus** [comment]
My thanks to you for accepting pull-requests in the first place :)

**Comment by sjh37** [comment]
You'll have to let me know when I can release all these in an update as you may be busy adding more :-)

**Comment by sjh37** [comment]
Released in v2.37.0

**Pull request merged**
