### PR TITLE
Allow Elements.UnitOfWork to be unset and remove some trailing spaces

### PR DESCRIPTION
**Pull request by yyjdelete**

### CODE REVIEW

**Comment by sjh37** [comment]
You've misunderstood what the Unit of work is about.
There must always be an interface generated.

e.g.

**Interfaces\** folder:
use Elements.UnitOfWork

**Elements\** folder
use Elements.Poco

**Context\** folder
use  Elements.Context | Elements.PocoConfiguration

In each of the above folders you add in the generator.
The elements folder will inherit the interface generated in the Interfaces folder.

Watch the pluralsight course on this project to understand this better.

**Comment by sjh37** [comment]
Read about SOLID, and coding against an interface, and not an implementation.
It allows for swapping out the real context for a fake one in your tests.

**Comment by yyjdelete** [comment]
Yes, I know that.
But what if I don't use UnitOfWork, and set  
`ElementsToGenerate = Elements.Poco | Elements.Context | Elements.PocoConfiguration;`
I must create an empty interface manually to avoid compile error?

``` C#
public interface IMyDbContext
{
//Do nothing
}
```

If UnitOfWork must be set, why export it?

**Comment by yyjdelete** [comment]
Yes, I know that.
But what if I don't use UnitOfWork and test, and set  
`AddUnitTestingDbContext = false;`
`ElementsToGenerate = Elements.Poco | Elements.Context | Elements.PocoConfiguration;`
I must create an empty interface manually to avoid compile error?

``` C#
public interface IMyDbContext
{
//Do nothing
}
```

If UnitOfWork must be set, why export it?

**Comment by sjh37** [comment]
Hi.
UnitOfWork must be set in one of the generators. Assuming you have different folders.
However, if you (like me) just use a single folder for most purposes, you must specify it. How else will you unit test your business logic by passing in a fake context with pre-configured test data?

I can only assume you are not unit testing your code, and not using dependency injection such as Castle, AutoFac, etc. However, you should really be coding against an interface, even if you don't want to test your code, as this is good practice.

If you really must code against the real thing, and wish to avoid using an interface, you will have to modify the code. However, this is not something I would make permanent within the generator, even if it was an option. I'd get slaughtered by the community, and by my fellow senior developers.

**Pull request closed without merging**
