### PR TITLE
Synonym foreign keys and stored procedures

### PR DESCRIPTION
**Pull request by TimSirmovics**
Added support and test cases for foreign key navigation properties (#110) and stored procedures when referencing objects through synonyms.

### CODE REVIEW

**Comment by sjh37** [comment]
Thanks Tim, much appreciated!

**Comment by sjh37** [comment]
Released in v2.35.0

**Comment by sjh37** [comment]
@TimSirmovics I've corrected a slight bug in the SQL. I had to change "UNION ALL" to "UNION" to remove duplicates. The duplicates were causing the code to generate many-to-may FK relationships instead of one-to-one in certain circumstances.

**Comment by dialedin2014** [comment]
@sjh37 @TimSirmovics Hi guys.  The database I am working has four tables, each setup like this:
Table1 (Synonym)
Table1_Load (Synonym)
Table1_A (Actual Table)
Table1_B (Actual Table)

In the tt file, I filter out everything but the synonym Table1.

The output does not have navigation properties.

I used SQL Profiler to obtain the SQL generated by Ef.Reverse.Poco.Core.ttinclude

This is the first statement with a resultset.  It begins on line 230 of Profiler's output.

'
SELECT  c.TABLE_SCHEMA AS SchemaName,
        c.TABLE_NAME AS TableName,
        t.TABLE_TYPE AS TableType,
        c.ORDINAL_POSITION AS Ordinal,
        c.COLUMN_NAME AS ColumnName,
        CAST(CASE WHEN IS_NULLABLE = 'YES' THEN 1
                  ELSE 0
             END AS BIT) AS IsNullable,
        DATA_TYPE AS TypeName,
        ISNULL(CHARACTER_MAXIMUM_LENGTH, 0) AS MaxLength,
        CAST(ISNULL(NUMERIC_PRECISION, 0) AS INT) AS Precision,
        ISNULL(COLUMN_DEFAULT, '') AS [Default],
        CAST(ISNULL(DATETIME_PRECISION, 0) AS INT) AS DateTimePrecision,
        ISNULL(NUMERIC_SCALE, 0) AS Scale,
        CAST(COLUMNPROPERTY(OBJECT_ID(QUOTENAME(c.TABLE_SCHEMA) + '.' + QUOTENAME(c.TABLE_NAME)), c.COLUMN_NAME, 'IsIdentity') AS BIT) AS IsIdentity,
        CAST(CASE WHEN COLUMNPROPERTY(OBJECT_ID(QUOTENAME(c.TABLE_SCHEMA) + '.' + QUOTENAME(c.TABLE_NAME)), c.COLUMN_NAME, 'IsIdentity') = 1 THEN 1
                  WHEN COLUMNPROPERTY(OBJECT_ID(QUOTENAME(c.TABLE_SCHEMA) + '.' + QUOTENAME(c.TABLE_NAME)), c.COLUMN_NAME, 'IsComputed') = 1 THEN 1
                  WHEN DATA_TYPE = 'TIMESTAMP' THEN 1
                  WHEN DATA_TYPE = 'UNIQUEIDENTIFIER'
                       AND LOWER(ISNULL(COLUMN_DEFAULT, '')) LIKE '%newsequentialid%' THEN 1
                  ELSE 0
             END AS BIT) AS IsStoreGenerated,
        CAST(CASE WHEN pk.ORDINAL_POSITION IS NULL THEN 0
                  ELSE 1
             END AS BIT) AS PrimaryKey,
        ISNULL(pk.ORDINAL_POSITION, 0) PrimaryKeyOrdinal,
        CAST(CASE WHEN fk.COLUMN_NAME IS NULL THEN 0
                  ELSE 1
             END AS BIT) AS IsForeignKey
FROM    #Columns c
        LEFT OUTER JOIN #PrimaryKeys pk
            ON c.TABLE_SCHEMA = pk.TABLE_SCHEMA
               AND c.TABLE_NAME = pk.TABLE_NAME
               AND c.COLUMN_NAME = pk.COLUMN_NAME
        LEFT OUTER JOIN #ForeignKeys fk
            ON c.TABLE_SCHEMA = fk.TABLE_SCHEMA
               AND c.TABLE_NAME = fk.TABLE_NAME
               AND c.COLUMN_NAME = fk.COLUMN_NAME
        INNER JOIN INFORMATION_SCHEMA.TABLES t
            ON c.TABLE_SCHEMA COLLATE DATABASE_DEFAULT = t.TABLE_SCHEMA COLLATE DATABASE_DEFAULT
               AND c.TABLE_NAME COLLATE DATABASE_DEFAULT = t.TABLE_NAME COLLATE DATABASE_DEFAULT
WHERE   c.TABLE_NAME NOT IN ('EdmMetadata', '__MigrationHistory')
        AND c.TABLE_NAME NOT LIKE 'sysdiagram%' 
UNION
-- Synonyms
SELECT SchemaName, TableName, TableType, Ordinal, ColumnName, IsNullable, TypeName, [MaxLength], [Precision],
    [Default], DateTimePrecision, Scale, IsIdentity, IsStoreGenerated, PrimaryKey, PrimaryKeyOrdinal, IsForeignKey FROM #SynonymDetails
'
The output includes the Synonyms, and correctly sets the IsForeignKey column.

Later on, the #SynonymFkDetails table is populated.  I noticed it contains all the FKs in the database, but there doesn't seem to be anything to match them with Synonyms.

[EF.Reverse.POCO.Core generated sql .txt](https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/files/1823059/EF.Reverse.POCO.Core.generated.sql.txt)

**Comment by TimSirmovics** [comment]
Hi @dialedin2014,

I think you are correct in that the synonyms foreign keys do not work properly if the synonym and original table do not have the same name.

If you could submit a PR to fix this that would be great, otherwise I will try and look at it when I have time.

**Pull request merged**
