### PR TITLE
Access modifiers on types can now be arbitrarily set.

### PR DESCRIPTION
**Pull request by daiplusplus**
I wanted to make my `{Entity}Configuration` classes `internal` while keeping my entity types `public` - and I got a bit carried away...

This represents a breaking change. Feedback appreciated.

### CODE REVIEW

**Comment by sjh37** [comment]
Actually I like what you've done and it's all the better for it.

**Comment by sjh37** [comment]
You can't use C#6 features as a lot of people are still on VS 2015, etc.
```c#
public static bool DbContextClassIsPartial => DbContextClassModifiers?.Contains("partial") ?? false;
```
becomes
```c#
public static bool DbContextClassIsPartial()
{
    return DbContextClassModifiers != null && DbContextClassModifiers.Contains("partial");
}
```

I'll make the changes :-)

**Comment by daiplusplus** [comment]
I also had the Elvis-operator in the access-modifiers-for-foreign-keys too, btw.

**Comment by sjh37** [comment]
Released in v2.37.0

**Pull request merged**
