### PR TITLE
Add my modifications and the IDbContext. Need to fix that.

### PR DESCRIPTION
**Pull request by wforney**
I wasn't sure about adding the IDbContext I created, but it seemed it was the one thing missing. It isn't working at present, I just want to start a conversation around it. The other changes I made add some /// comments and things I always do when I use the template.

### CODE REVIEW

**Comment by sjh37** [comment]
You change so much, I won't be able to pull this in without breaking things.
However, I can incorporate somethings manually.
I'll take a look at this later when I have time.

**Comment by ErikEJ** [comment]
This is not a useful PR

**Comment by wforney** [comment]
Well, I threw in all the changes I usually do. Due to adding the interface for IDbContext the build on it is broken, which I noted. I can do some smaller tweaks and send parts of it at a time if that's easier.

**Comment by ErikEJ** [comment]
@wforney  Yes, one small feature at a time - that's how great software is built

**Comment by sjh37** [comment]
@wforney I'll reject this pull request as I can't use it. Please use much smaller changes :-)
Smaller the better.

**Pull request closed without merging**
