### PR TITLE
New option to add a default IDbContextFactory<DbContextName> implementation

### PR DESCRIPTION
**Pull request by 0xced**

### CODE REVIEW

**Comment by sjh37** [comment]
Thanks. This will be in the next release.

**Comment by sjh37** [comment]
v2.33.0 Released.

**Comment by StevenBonePgh** [comment]
I like this option, but I believe the class should be generated as a partial.

**Comment by sjh37** [comment]
@StevenBonePgh I've added `partial` to the declaration of `IDbContextFactory` if  `Settings.MakeClassesPartial = true;`
So it's now up to user if they want it or not. Is this ok, or did you want it always partial, regardless if `Settings.MakeClassesPartial` is set or not?

**Comment by StevenBonePgh** [comment]
Good question, I could go either way on the answer. I'd guess that because there is no real other hook that changes other elements of the codegen (like the addition of calling `InitializePartial()`) most people wouldn't be concerned with always emitting it.  The binary decision to use partial or not is pretty clear as to the type of code that is generated, so that is also good.  I'd leave it they way you implemented it.  Thanks for adding this - I don't actually have a use case at the moment, but I had a couple of thoughts after seeing it and thought making it partial would make it a bit more flexible.

**Comment by sjh37** [comment]
Released in v2.35.0

**Pull request merged**
